configure script improvement

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,10 +11,19 @@ pkgmgrs[/etc/arch-release]=pacman
 pkgmgrs[/etc/gentoo-release]=emerge
 pkgmgrs[/etc/SuSE-release]=zypp
 pkgmgrs[/etc/debian_version]=apt-get
+
 for f in ${!pkgmgrs[@]}; do
     if [[ -f $f ]]; then
         export PKG_MGR="${pkgmgrs[$f]}"
     fi
 done
-$PKG_MGR update
-$PKG_MGR install $NCURSES
+
+if [ "$PKG_MGR" != "" ]; then
+    $PKG_MGR update
+    $PKG_MGR install $NCURSES
+else
+    echo "Failed to install ncurses; couldn't locate a " \
+         "package manager for your system."
+    exit 1
+fi
+exit 0
